# Generated by Django 3.0.5 on 2020-05-02 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('apple', 'apple'), ('banana', 'banana'), ('orange', 'orange'), ('strawberry', 'strawberry'), ('beetroot', 'beetroot'), ('carrot', 'carrot'), ('celery', 'celery'), ('cucumber', 'cucumber')], max_length=50)),
                ('type', models.IntegerField(choices=[(1, 1), (2, 2)])),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=36)),
                ('has_died', models.BooleanField()),
                ('balance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('picture', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('eye_colour', models.CharField(choices=[('blue', 'blue'), ('brown', 'brown')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('female', 'female'), ('male', 'male"')], max_length=20)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('about', models.TextField()),
                ('registered', models.DateTimeField()),
                ('greeting', models.CharField(max_length=200)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='colonyfriends.Company')),
                ('favourite_foods', models.ManyToManyField(to='colonyfriends.Food')),
                ('friends', models.ManyToManyField(related_name='_person_friends_+', to='colonyfriends.Person')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='colonyfriends.Person')),
            ],
        ),
    ]
